services:
  - type: web
    name: smart-mebel
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --preload --bind 0.0.0.0:$PORT
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      # Оставьте DATABASE_URL пустым для SQLite (только для теста)
      # - key: DATABASE_URL
      #   value: postgres://USER:PASSWORD@HOST:PORT/DBNAME
    routes:
      - type: rewrite
        source: /.well-known/*
        destination: /.well-known/*
